name: Build MeepMeep

on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build MeepMeep
        run: ./gradlew --no-daemon build

      - name: Test MeepMeep
        run: ./gradlew --no-daemon test

