name: Trigger JitPack Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-jitpack-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger JitPack Build
        run: |
          curl -L "https://jitpack.io/api/builds/$GITHUB_REPOSITORY/${GITHUB_SHA:0:10}"